# Semantic PRs config file (https://github.com/Ezard/semantic-prs)

enabled: true
titleOnly: true
allowRevertCommits: true
types:
  - feat
  - fix
  - chore
  - ci
  - docs
  - refactor
  - style
  - test
  - revert
  - build
  - release
