name: kana_kit
description: >
  A Dart library for handling and converting Japanese
  characters such as hiragana, katakana and kanji.
version: 1.0.1
homepage: https://pub.dev/packages/kana_kit
repository: https://github.com/jeroen-meijer/kana_kit

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.2
  meta: ^1.1.8
  test: ^1.15.3

dev_dependencies:
  effective_dart: 1.2.3
  pedantic: 1.9.0
  test_coverage: 0.4.3
