name: kana_kit
description: >
  A Dart library for for detecting and transliterating Hiragana, Katakana, and
  Romaji.
version: 2.0.0
repository: https://github.com/jeroen-meijer/kana_kit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: 2.0.0

dev_dependencies:
  test: 1.16.5
  test_coverage: 0.5.0
  very_good_analysis: 1.0.4
