name: kana_kit
description: >
  A Dart library for for detecting and transliterating Hiragana, Katakana, and
  Romaji.
version: 2.1.0
repository: https://github.com/jeroen-meijer/kana_kit

environment:
  sdk: "^3.0.0"

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  coverage: ^1.6.3
  test: any
  very_good_analysis: any
