name: kana_kit
description: >
  A Dart library for for detecting and transliterating Hiragana, Katakana, and
  Romaji.
version: 2.1.0
repository: https://github.com/jeroen-meijer/kana_kit

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  checks: ^0.3.0
  collection: ^1.19.0
  meta: ^1.16.0

dev_dependencies:
  coverage: 1.9.2
  test: 1.25.8
  very_good_analysis: 6.0.0
