name: kana_kit
description: >
  A Dart library for for detecting and transliterating Hiragana, Katakana, and
  Romaji.
version: 2.1.0
repository: https://github.com/jeroen-meijer/kana_kit

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  coverage: ^1.7.2
  test: ^1.25.1
  very_good_analysis: ^5.1.0
