name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  kana_kit:
    runs-on: ubuntu-latest
    container:
      image: "google/dart:2.8.4"
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Dry run publish
        id: dry_run_publish
        uses: k-paxian/dart-package-publisher@master
        with:
          dryRunOnly: true
          skipTests: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}

      - name: Compare versions
        if: ${{ steps.dry_run_publish.outputs.localVersion == steps.dry_run_publish.outputs.remoteVersion }}
        run: |
          echo "Local package version number ${{steps.dry_run_publish.outputs.localVersion}} and remote pub version number ${{steps.dry_run_publish.outputs.remoteVersion}} are the same. Update the local version number."
          exit 1

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Test
        run: pub run test_coverage

      - name: Publish codecov
        shell: bash
        run: bash <(curl -s https://codecov.io/bash)

      - name: Check codecov
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: ./coverage/lcov.info
          exclude: "**/*.g.dart lib/src/models/romanization/**"
          min_coverage: 99

          name: Publish plugin
