name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  kana_kit:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Test
        run: pub run test_coverage

      - name: Dry run publish
        run: |
          echo "Copy credentials"
          mkdir -p ~/.pub-cache
          echo "$CREDENTIAL_JSON" > ~/.pub-cache/credentials.json 
          echo "Run pub publish --dry-run"
          pub publish --dry-run
        env:
          CREDENTIAL_JSON: ${{ secrets.CREDENTIAL_JSON }}

      - name: Publish codecov
        shell: bash
        run: bash <(curl -s https://codecov.io/bash)

      - name: Check codecov
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: ./coverage/lcov.info
          exclude: "**/*.g.dart lib/src/models/romanization/**"
          min_coverage: 99
