name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  kana_kit:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Dry run publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          dry_run: true
          skip_test: true
          flutter_package: false
          credential: ${{ secrets.CREDENTIAL_JSON }}

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Test
        run: pub run test_coverage

      - name: Publish codecov
        shell: bash
        run: bash <(curl -s https://codecov.io/bash)

      - name: Check codecov
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: ./coverage/lcov.info
          exclude: "**/*.g.dart lib/src/models/romanization/**"
          min_coverage: 99
