name: Draft Release
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Add pub executables to path
        run: echo "::add-path::$HOME/.pub-cache/bin"

      - name: Set pub version in env
        run: |
          pub global activate pubspec_version
          echo "Current version is: $(pubver get)"
          echo "::set-env name=RELEASE_VERSION::$(pubver get)"

      - name: Create release draft
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          name: v${{ env.RELEASE_VERSION }}
          version: ${{ env.RELEASE_VERSION }}
          tag: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
