name: publish_to_pub
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to pub
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          skipTests: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}

      - name: Verify published
        run: |
          if [ "${{steps.publish.outputs.success}}" = "false" ]; then
            echo "Publishing failed."
            exit 1
          else
            exit 0
          fi
