name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Copy credentials"
          mkdir -p ~/.pub-cache
          echo echo "$CREDENTIAL_JSON" > ~/.pub-cache/credentials.json 
          echo "Run pub publish --force"
          pub publish --force
        env:
          CREDENTIAL_JSON: ${{ secrets.CREDENTIAL_JSON }}