name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Copy credentials"
          mkdir -p ~/.pub-cache
          cat ${{ secrets.CREDENTIAL_JSON }} > ~/.pub-cache/credentials.json
          echo "Run pub publish"
          pub publish